### ISSUE TITLE
Whitespace [UBL]

### ISSUE THREAD

**Issue by SLennartsson** [ConnectingEurope/eInvoicing-EN16931#114]
There is a fatal rule saying that a document must not contain empty elements. But linked to this there are serious issues with the use of whitespace that has to be addressed.

1. It is possible to bypass the “empty element” rule by means of whitespace.

As an example, one may generate an invoice with only whitespace in BT-1 Invoice number (Invoice/ID). The business term is mandatory in EN 16931, but no validation rule is triggered!
```xml
…
<cbc:CustomizationID>urn:cen.eu:en16931:2017#compliant#urn:fdc:peppol.eu:2017:poacc:billing:3.0</cbc:CustomizationID>
<cbc:ProfileID>urn:fdc:peppol.eu:2017:poacc:billing:01:1.0</cbc:ProfileID>
<cbc:ID>	   </cbc:ID>
<cbc:IssueDate>2018-02-08</cbc:IssueDate>
…
```

2. Whitespace “surrounding a value” is treated differently by the validation rules. 

For example (using “single space character” to represent whitespace in general:
a) `<cbc:TaxAmount currencyID="SEK"> 100 </cbc:TaxAmount>` would be accepted 
b) `<cbc:IssueDate> 2018-07-31 </cbc:IssueDate>` would generate error signal “A date MUST be formatted YYYY-MM-DD.” [How many will understand what to correct?]
c) `<cbc:IdentificationCode> AF </cbc:IdentificationCode>` would generate error signal “Country code MUST be according to ISO 3166 Alpha-2.” [How many will understand what to correct?]

3. Unless very clear rules are given, whitespace may play tricks on stylesheet visualization. To some extent this could be argued as a task for the stylesheet designers, but for consistency reasons the basic principles for the handling of whitespace must be set centrally.

A simple UBL-XML example is attached illustrating situations where all three categories of problems are demonstrated.

Request: Address how whitespace are to dealt with in UBL invoicing messages and arrange for the appropriate validation rules. 

[Invoice_ WithLessThenMinimumContent.pdf](https://github.com/CenPC434/validation/files/2860963/Invoice_.WithLessThenMinimumContent.pdf)
[SampleInvoice_AsPresentedWithSFTIStylesheet.pdf](https://github.com/CenPC434/validation/files/2860972/SampleInvoice_AsPresentedWithSFTIStylesheet.pdf)

**Comment by kosek** [comment]
On 13.2.2019 16:35, SLennartsson wrote:
> 2. Whitespace “surrounding a value” is treated differently by the validation rules. 
>
> For example (using “single space character” to represent whitespace in general:
> 
> a) <cbc:TaxAmount currencyID="SEK"> 100 </cbc:TaxAmount> would be accepted 
> 
> b) <cbc:IssueDate> 2018-07-31 </cbc:IssueDate> would generate error signal “A date MUST be formatted YYYY-MM-DD.” [How many will understand what to correct?]
> 
> c) cbc:IdentificationCode> AF </cbc:IdentificationCode> would generate error signal “Country code MUST be according to ISO 3166 Alpha-2.” [How many will understand what to correct?]

Whitespace is normalized prior validation in XSDs with an exception of
xs:string type. So a) and b) shouldn't produce any validation errors
agains XSD.

For 3) it would be enough to base this data type on xs:token rather than
on xs:string.

> 3. Unless very clear rules are given, whitespace may play tricks on stylesheet visualization. To some extent this could be argued as a task for the stylesheet designers, but for consistency reasons the basic principles for the handling of whitespace must be set centrally.

Really? Whitespace is normalized in web browsers in a similar way so it
is quite unlikely that this would cause any troubles.

> Request: Address how whitespace are to dealt with in UBL invoicing messages and arrange for the appropriate validation rules. 

I'm not sure that this would help. As in any interchange scenario you
should be strict about what you produce and liberal on what you accept.
So when producing invoices you should not put any extra whitespace into
output, but when accepting invoice you should ignore whitespace in all
elements that are not xs:string or mixed content.

					Jirka

-- 
------------------------------------------------------------------
  Jirka Kosek      e-mail: jirka@kosek.cz      http://xmlguru.cz
------------------------------------------------------------------
     Professional XML and Web consulting and training services
DocBook/DITA customization, custom XSLT/XSL-FO document processing
------------------------------------------------------------------
    Bringing you XML Prague conference    http://xmlprague.cz
------------------------------------------------------------------

**Comment by oriol** [comment]
As far as I see, we should normalize prior to validate dates and codes to avoid this issue. 

This would mean that the receiving end would need to do the same. As Jirka says, receivers should be liberal on what they accept.

However, changing this needs discussion and agreement in the TC.

**Comment by kosek** [comment]
Hi, as agreed on the TC meeting last week I'm going to summarize problem and changes needed in a few separate comments. 

Let's start with dates. Currently Schematron compares dates as strings, for example in BR-29:

`(cbc:EndDate) &gt;= (cbc:StartDate)`

However this means that whitespace is taken into account when comparing dates. So for example whereas the following is correctly marked as invalid:

````xml
    <cac:InvoicePeriod>
        <cbc:StartDate>2013-06-01</cbc:StartDate>
        <cbc:EndDate>2013-05-30</cbc:EndDate>
    </cac:InvoicePeriod>
````

because start date is later then end date. However just by adding space before the first date it's lexical value is now lesser then for end date (because space character has lower code point in the Unicode then numbers). So the current Schematron marks wrongly following as a valid content:

````xml
    <cac:InvoicePeriod>
        <cbc:StartDate> 2013-06-01</cbc:StartDate>
        <cbc:EndDate>2013-05-30</cbc:EndDate>
    </cac:InvoicePeriod>
````

Please note space after `<cbc:StartDate>` and before `2013-06-01`. 

As spaces are not significant for xs:date datatypes (they are normalized prior validation) such added space shouldn't have impact on validation in Schematron as well. Proper approach is to cast date values to xs:date type and compare real dates in Schematron. So rule for BR-29 UBL should be rewritten as:

````xml
<param name="BR-29" value="(exists(cbc:EndDate) and exists(cbc:StartDate) and xs:date(cbc:EndDate) ge xs:date(cbc:StartDate)) or not(exists(cbc:StartDate)) or not(exists(cbc:EndDate))"/>
````

So for values that contain dates all rules should be rewritten in the similar way to give consistent validation results.

**Comment by kosek** [comment]
For boolean values Schematron is currently comparing values against true() or false(). This will automatically cast second part of comparision to xs:boolean (see rules at https://www.w3.org/TR/xpath20/#id-general-comparisons) and produce correct results irrespective of whitespace because during casting whitespace is normalized according to rules for casted type.

So for example expression like `cbc:ChargeIndicator=true()` behaves as if content coming from the XML document were explicitly casted using `xs:boolean(cbc:ChargeIndicator)=true()`

I think it would be good to update Schematron to make such explicit calls to xs:boolean to make it clear what is going on there. Not everyone knows automatic casting rules of XPath. Also call to xs:boolean makes it little bit more clear that any xs:boolean (0, 1, false, true) is supported.

**Comment by kosek** [comment]
As for numbers -- Schematron already casts them using xs:decimal, so there is no problem. And whitespace around numbers is correctly ignored.

**Comment by kosek** [comment]
For string based values situation is more complex. I have looked only into UBL, someone should do the same for CII.

Whitespace normalization rules are different for types xs:string, xs:normalizedString and xsd:token -- and types that are derived from them. 

UBL schemas are not using xs:token type that is doing whitespace normalization. Instead string based types are based on xs:string or xs:normalizedString. 

xs:string serves as a base for free text fields like notes, names, etc.

xs:normalizedString is generally used for various codes. xs:normalizedString doesn't strip leading and trailing whitespace nor removes consecutive spaces. It only turns CR, LF and TAB characters into spaces.

Schematron rules should implement whitespace processing consistent with the rules above. This means that normalize-space() function should not be called in most situations as this would validate values containing excessive spaces. Schematron schema should be carefully inspected and such calls to normalize-space() should be removed.

On the other hand for values that are based on xs:normalizeString and that could contain spaces custom function doing normalization consistent with XML schemas should be invoked before value is further checked.

**Comment by kosek** [comment]
As situation around whitespace processing is more complicated than it should be it would be useful to have some sort of tutorial on how to deal with whitespace in EU invoices.

**Comment by oriol** [comment]
> Schematron rules should implement whitespace processing consistent with the rules above. This means that normalize-space() function should not be called in most situations as this would validate values containing excessive spaces. Schematron schema should be carefully inspected and such calls to normalize-space() should be removed.

Currently, normalize-space() is only used when checking codes or identifiers that act as a code, namely PaymentMeansCode and the VAT category identifier. 

I would not add any other type of whitespace processing in any other string based value.

**Comment by SLennartsson** [comment]
Hi Oriol,



I am happy to leave this discussion in the able hands of yourself and your colleagues but, as the technical level is too advanced for me, I’d just like to verify that section 6.5.10 of EN and section 6.2.9 of BIS Billing 3 are not compromised.



Regards,

Sören

**Comment by oriol** [comment]
In CII xs:date() cannot be used in DateTimeString.

**Comment by kosek** [comment]
> In CII xs:date() cannot be used in DateTimeString.

You can use xs:dateTime() for xs:dateTime values.

**Comment by oriol** [comment]
The element is a string, not an xs:dateTime...

**Comment by phax** [comment]
Peppol added an additional rule on top of the CEN rules explicitly verifying, that no empty elements are contained: 

PEPPOL-EN16931-R008 (fatal) : Document MUST not contain empty elements.
```xml
//[not() and not(normalize-space())]
```

Source: https://docs.peppol.eu/poacc/billing/3.0/bis/#peppol_rules
