### ISSUE TITLE
Use of BG-3 in CrossIndustryInvoice

### ISSUE THREAD

**Issue by lasjan** [ConnectingEurope/eInvoicing-EN16931#207]
According to EN16931 mapping to Industry Invoice D16B, there should be possiblity of creating multiple BG-3 elements (cardinality is 0..n), whilst CII xsd allows using this BG only once:

<xsd:element name="InvoiceReferencedDocument" type="ram:ReferencedDocumentType" minOccurs="0"/>

What is proper approach for this issue? Is there some kind of formatting defined for embedding multiple preceding invoice numbers and dates in single field?

BR,
Marcin

**Comment by oriol** [comment]
According to the mapping, there are no options to add more than one BG-3 elements using CII. 
I would raise this issue in the TC 434 for them to assess how to resolve it.

**Comment by svanteschubert** [comment]
For sure, in EN16931 syntax binding to CII a CAR-4  is missing as the source (semantic) got X..N and the target (CII XML) has X..1.

And Gerhard Heemskerk (working on UN/CEFACT formats) mentioned:
"The possibility to refer to more than one preceding invoice has been effected in the library D19B. The messages for D19B have not been published, it should have been. But anyway the will be soon.
Header_ Trade Settlement. Invoice. Referenced_ Document à made unbounded in D19B."

@oriol Where did you raise the issue in TC 434? I suggest not to close an issue unless it is completely finished, like for instance providing feedback from the TC 434, otherwise, we could lose track of unfinished work.

**Comment by oriol** [comment]
I did not raise the issue, I recommended @lasjan to raise it in the TC. Maybe you can do it on his behalf.

This github is to deal with issues on validation artefacts. The issues related to the standard are to be reported in TC 434.

**Comment by homebeaver** [comment]
> 
> 
> ...  I suggest not to close an issue unless it is completely finished, like for instance providing feedback from the TC 434, otherwise, we could lose track of unfinished work.

Hi @svanteschubert - you are right. This issue should not be closed.

@oriol - I suggest to mark this issue with Label "`CEN/TC 434 issue`" or "`EN 16931 issue`" or similar and reopen it.

regards EUGen

**Comment by phax** [comment]
I agree - so that we're keeping track on where discussion is still needed, and where we have finished the discussion already

**Comment by homebeaver** [comment]
👍

**Comment by phax** [comment]
Okay, after thorough discussion it was decided to close this issue again. Please bring this forward with your national standardization body - we cannot trigger this from here.
