### ISSUE TITLE
PartyTaxScheme not validated (correctly)

### ISSUE THREAD

**Issue by ConnectingEurope** [ConnectingEurope/eInvoicing-EN16931#230]
Hi.

The tag PartyTaxScheme is not validated (correctly) in the schematron. 

1. Cardinality: It is possible to have multiple PartyTaxScheme's (see file) but the specification (https://docs.peppol.eu/poacc/billing/3.0/syntax/ubl-invoice/cac-AccountingCustomerParty/cac-Party/) only allows 1 on CustomerParty-level.

2. ID shall contain VAT: In these multiple TaxScheme's, a different value than VAT that is allowed when the specification does not (https://docs.peppol.eu/poacc/billing/3.0/syntax/ubl-invoice/cac-AccountingCustomerParty/cac-Party/cac-PartyTaxScheme/cac-TaxScheme/)

Kind regards,
Geoffrey De Kerpel
Resolution

Forward to tc-434
The tax identifier bt-32 is allowed for the seller, it shoud not be allowed for the buyer.
The schematron rules seems to allow both.
[BIS3-PartyTaxScheme(1).txt](https://github.com/ConnectingEurope/eInvoicing-EN16931/files/5210185/BIS3-PartyTaxScheme.1.txt)

Originates from https://openpeppol.atlassian.net/browse/PEPPOL-2317

**Comment by oriol** [comment]
The EN has two different Business Terms, BT-31 and BT-32, both mapped to 

cac:AccountingSupplierParty/cac:Party/cac:PartyTaxScheme/cbc:CompanyID 

BT-31 shall have a cac:TaxScheme/cbc:ID = “VAT" and BT-32 shall have cac:TaxScheme/cbc:ID != “VAT"

That's why there are two rules

[UBL-SR-12]-Seller VAT identifier shall occur maximum once
[UBL-SR-13]-Seller tax registration shall occur maximum once

That check that:

(count(cac:AccountingSupplierParty/cac:Party/cac:PartyTaxScheme[cac:TaxScheme/upper-case(cbc:ID)='VAT']/cbc:CompanyID) &lt;= 1)"

(count(cac:AccountingSupplierParty/cac:Party/cac:PartyTaxScheme[cac:TaxScheme/upper-case(cbc:ID)!='VAT']/cbc:ID) &lt;= 1)"

I notice that UBL-SR-13 is wrong as it checks for cbc:ID instead of cbc:CompanyID and this could be the problem.
