### ISSUE TITLE
Validation rule BR-CO-25 

### ISSUE THREAD

**Issue by ConnectingEurope** [ConnectingEurope/eInvoicing-EN16931#232]
Ref BR-CO-25 : “In case the Amount due for payment (BT-115) is positive, either the Payment due date (BT-9) or the Payment terms (BT-20) shall be present.”
Issue: It is appreciated that EN 16931-1 does not sufficiently well describe the intentions with BR-CO-25, and that it technically is inaccurate. In consequence of this, Peppol had to introduce an amendment through the August 2019 hotfix. However, this hotfix brought several flaws (addressed in other RfC:s). 
Suggestion: As Peppol obviously has to make a deviation from EN16931-1, a better option is to suspend implementation of rule BR-CO-25 all together (incl. to reverse the resolve of #84). For example, Swedish framework agreements may have a clause on payment terms that make BT-19 and BT-20 unnecessary (and, if yet present in a transaction, BT-9/BT-20 would be overruled by what is set in the framework agreement) – in such use cases rule BR-CO-25 carries no meaning. 
Resolution

Forward it to tc-434 suggesting to extend the context of BR-CO-25 to be also relevant to negative Credit Notes.

Originates from Peppol https://openpeppol.atlassian.net/browse/POACC-306

**Comment by oriol** [comment]
The BR-CO-25 excludes several real-life use case scenarios, where individual invoices do not carry due date for payment or payment terms nor have to carry them.

Apart from that, the rule forces due dates or payment terms in Credit Notes and in negative invoices, which is not logical.

The suggestion is to remove the rules, and as this is backwards compatible, amend the EN accordingly.

**Comment by midran** [comment]
Referring to TC434 WG1 meeting on 2020-09-30. In the meeting, when discussing a different issue but with reference to this one, it as agreed to remove rule BR-CO-25. This closes this issue.

**Comment by csautereau** [comment]
BR-CO-25 is still present in Revised EN16931 2026, which is just approved.
There is no reason to decide to delete it because PEPPOL has made a deviation.

The EN16931 should be respected, also by PEPPOLBIS which is a CIUS.
There is no reason to aligne CII with deviation of PEPPOL

The rule is "In   case   the   Amount   due   for   payment   (BT-115)   is positive,  either  the  Payment  due  date  (BT-9)  or  the Payment terms (BT-20) shall be present.".

 I understand that in case of a Credit note, it coud be discussed the presence of a BT-9 / Payment Terms, knowing that a due Date for a Credit note means something, especially if the credit note needs a reimbursement.

BR-CO-25 should not be deleted in CII (and neither in UBL).

**Comment by svanteschubert** [comment]
I would like to second Cyrille’s request.

BR-CO-25 is part of EN 16931 and, as Cyrille pointed out, is still present in the approved 2026 revision. Therefore, it should not be removed from the EN 16931 validation artefacts without a corresponding decision by CEN/TC 434.

I would also like to ask the maintainers to actively bring issues labelled “CEN/TC 434 Discussion needed” to CEN/TC 434 WG 1 (Semantics), so that such changes can be discussed and decided within the appropriate standardisation body before they are reflected in the validation artefacts
