### ISSUE TITLE
Support for VAT category code B, supporting Italian A-deviation

### ISSUE THREAD

**Issue by ConnectingEurope** [ConnectingEurope/eInvoicing-EN16931#236]
From: Paul Simons <Paul.Simons@codabox.com> 
Sent: mánudagur, 7. september 2020 13:15
To: CEF-EINVOICING-SUPPORT@ec.europa.eu
Cc: Georg Birgisson (georg@midran.is) <georg@midran.is>; Bertocchi Elisa <Elisa.Bertocchi@regione.emilia-romagna.it>
Subject: Adding CODE B to the 

Dear,

As convenor of TC434 WG1, I would like to file the below RFC to the Tax Category Code list (Subset of UNCL5305) used in the EN16931.

To support the IT A-Deviation to the EN16931 granted to Italy, can the Tax Category CODE “B” be added to the codelist please.

Thanks in advance to consider this RFC.

Groeten,
Bien à vous,
Kind regards,

Paul SIMONS
e-Ambassador

T: +32 2 880 84 80
M: +32 475 34 57 13
paul.simons@codabox.com
www.codabox.com

**Comment by oriol** [comment]
Adding a new code in the Tax Category Code codelist is not as easy as it may seem. 

At least, there are two points that should be taken into account:

1) In the current model, there are many rules that use the tax category code for calculations, so there should be an assessment of the impact of adding such a code in the model.

2) Adding this code in the code list means that  everybody will have to understand and process it. This represents a high impact for the current users of the EN model.

In order to add this code then, i would suggest to:

a) Obtain different examples of invoice files with this B code, depicting the different use scenarios that can be represented with it. 
b) Perform a deep impact assessment of the consequences for the current instance and business rules, to avoid problems in the calculation model. 
c) Explain to the users community the way this new code has to be treated to avoid rejection problems.

As this is not a technical amendment of the business rules, I think the TC 434 has to discuss and provide the material to include it.

**Comment by oriol** [comment]
Comment from Italy:

In any case we sholud add at least two rules:

[BR-B-01]-An Invoice where the VAT category code (BT-151, BT-95 or BT-102) is “Split payment” shall be a domestic Italian invoice.

[BR-B-02]-An Invoice that contains an Invoice line (BG-25), a Document level allowance (BG-20) or
a Document level charge (BG-21) where the VAT category code (BT-151, BT-95 or BT-
102) is “Split payment" shall not contain an invoice line (BG-25), a Document level allowance (BG-20) or
a Document level charge (BG-21) where the VAT category code (BT-151, BT-95 or BT-
102) is “Standard rated”.

BR-B-02 is because we cannot combine category code S and category code B.

**Comment by oriol** [comment]
Resolved in commit 

https://github.com/ConnectingEurope/eInvoicing-EN16931/commit/273cd25990ac769c089682680357ec1784b02291
