### ISSUE TITLE
Logic error in BR-53 for CII

### ISSUE THREAD

**Issue by christian-schlichtherle** [ConnectingEurope/eInvoicing-EN16931#243]
https://github.com/ConnectingEurope/eInvoicing-EN16931/blob/273cd25990ac769c089682680357ec1784b02291/cii/schematron/CII/EN16931-CII-model.sch#L58

This is most likely wrong: I suppose the last `not` should be removed or otherwise it's a requirement that the `TaxCurrencyCode`, if present at all, must be different than the `InvoiceCurrencyCode` (say, one in EUR and the other one in USD).

Also, the second operand after the first `or` is redundant. If there is no `TaxCurrencyCode` then you don't need to test its absence again.

**Comment by oriol** [comment]
Yes, the requirement is that if the TaxCurrencyCode exists, it shall be different from the InvoiceCurrencyCode. If it is the same, it shall not exist.

**Comment by christian-schlichtherle** [comment]
Well, this is a bit of a surprise because in a previous version (the one used in XRechnung 1.2, don't know which exactly) you could actually specify both currency codes with the same value (say EUR) and it was accepted. Now an equivalent XML document would be rejected. This looks like a regression. IMHO it should not be an error if both currency codes are equal.

Actually, I cannot think of a scenario where it would be even desirable to specify a different currency code for the net invoice amount than for the value added tax amount, say one in USD and the other one in EUR.

**Comment by oriol** [comment]
The rule refers to BT-6 and BT-111.

[BR-53]-If the VAT accounting currency code (BT-6) is present, then the Invoice total VAT amount in accounting currency (BT-111) shall be provided.

The usage note in the EN for BT-6 is:

_Shall be used in combination with the Invoice total VAT amount in accounting currency (BT-111) **when the VAT
accounting currency code differs from the Invoice currency code.** The lists of valid currencies are registered
with the ISO 4217 Maintenance Agency “Codes for the representation of currencies and funds”. Please refer to Article 230 of the Council Directive 2006/112/EC [2] for more information._

That's why it has been implemented that way. In UBL is also implemented in the same way.

**Comment by christian-schlichtherle** [comment]
OK, thanks.
