### ISSUE TITLE
Function current() - Problem with the offline validation of EDIFACT instances

### ISSUE THREAD

**Issue by seppbrathansel** [ConnectingEurope/eInvoicing-EN16931#25]
When I check any of the currently available EDIfact instances in the downloaded version of the validator then I get for all 10 files the same kind of problem which stops the checking. See screenshot (check 1 line below the highlighted lines)

![grafik](https://cloud.githubusercontent.com/assets/25059758/21855204/df1b0914-d81d-11e6-8e25-dc415a9deac4.png)

**Comment by phax** [comment]
`current()` was changed to `.` - so this one is resolved. Follow up is #26

**Comment by phax** [comment]
According to Saxon docs, "current()" should be supported everywhere:
http://www.saxonica.com/html/documentation/functions/fn/current.html

**Comment by phax** [comment]
Problem solved.
Previously a Schematron dialect using only XPath was allowed.
`current()` is an XSLT function and not an XPath version and that's why the tests failed previously.
Now it was changed to use XSLT based validation and it works, but it is horribly slow.
-> This is addressed in a separate issue
