### ISSUE TITLE
Validation error BR-CO-16

### ISSUE THREAD

**Issue by senikk** [ConnectingEurope/eInvoicing-EN16931#255]
A customer has sent an invoice as shown below. I can’t see anything wrong with it but for those who have upgraded to the latest version of the validator artifacts it says its wrong:
![image](https://user-images.githubusercontent.com/400752/101517459-11f89400-3981-11eb-82aa-3a0d1f01f140.png)

0.00 (PayableAmount – BT-115) = 4500.00 (TaxInclusiveAmount – BT-112) - 4500.00 (PrepaidAmount – BT-113) + 0.00 (PayableRoundingAmount – BT-114)

In my head this is 0.00 = 0.00 

![image](https://user-images.githubusercontent.com/400752/101517432-0c9b4980-3981-11eb-994e-2325b84f80b4.png)

**Comment by phax** [comment]
See #242 on a work around

**Comment by senikk** [comment]
I could add the workaround, but to bad I have to throw away my time because your group have messed up your release. I have got lots of error reports from other accesspoint now using this latest release.

**Comment by juskoljo** [comment]
There is no process to have hotfixes for EN16931? @phax

**Comment by phax** [comment]
Passing this on to @oriol - I am no longer actively involved. Just commenting on a voluntary/personal basis

**Comment by juskoljo** [comment]
Ah good to know, thanks Philip! :)

**Comment by oriol** [comment]
The problem is not only on fixing the EN16931 validation artefacts but also on how they are adopted and used in different user communities.

We decided to publish a note instead of issuing a hotfix release of the 1.3.3 because it could have caused a negative impact on organizations alreeady using them. 

Based on your new input, we will work again on the process for hotfixes and will take action on this particular issue.

Thanks @phax for your support on this.

**Comment by oriol** [comment]
Duplicated from #242
