### ISSUE TITLE
[CII] BR-E-08, BR-E-09 and BR-E-10 are not triggered, the parent rule has wrong XPath selection

### ISSUE THREAD

**Issue by tavi-cacina** [ConnectingEurope/eInvoicing-EN16931#258]
This Rule has wrong selection: 
`<xsl:template match="//rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeSettlement/ram:ApplicableTradeTax/ram:CategoryCode[. = 'E'][upper-case(ram:TypeCode) = 'VAT']" mode="M10" priority="1024">`

The TypeCode is not a child of CategoryCode, it is a sibling, so you have to add the '../' prefix. The match selection should then be:

`<xsl:template match="//rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeSettlement/ram:ApplicableTradeTax/ram:CategoryCode[. = 'E'][upper-case(../ram:TypeCode) = 'VAT']" mode="M10" priority="1024">`

**Comment by tavi-cacina** [comment]
Forgot to mention, the Problem is only in the CII profile.

**Comment by tavi-cacina** [comment]
It seems the BR-G-, BR-AE- and BR-IC-08 -09 -10 have the same issue.

**Comment by oriol** [comment]
Still pending to solve the same issue in BR-O- rules.

**Comment by oriol** [comment]
BR-O rules do not have the issue as the rule XPATH is 
ram:ApplicableTradeTax[ram:CategoryCode = 'O'][upper-case(ram:TypeCode) = 'VAT'] 

instead of ram:ApplicableTradeTax/ram:CategoryCode [ .= 'O'][upper-case(ram:TypeCode) = 'VAT'] 

so no need for updating to [upper-case(../ram:TypeCode) = 'VAT'] as it is not a sibling of ApplicableTradeTax.
