### ISSUE TITLE
[CII-SR-119] allow charges on items

### ISSUE THREAD

**Issue by jstaerk** [ConnectingEurope/eInvoicing-EN16931#265]
The file 
[xrechnung2.txt](https://github.com/ConnectingEurope/eInvoicing-EN16931/files/5888624/xrechnung2.txt)
fires a 
`[CII-SR-119] - Only allowances on price a price should be present` in the test
`(ram:GrossPriceProductTradePrice/ram:AppliedTradeAllowanceCharge/ram:ChargeIndicator[udt:Indicator=false()] and ram:GrossPriceProductTradePrice/ram:AppliedTradeAllowanceCharge/ram:ActualAmount) or (not (ram:GrossPriceProductTradePrice/ram:AppliedTradeAllowanceCharge/ram:ChargeIndicator) and not (ram:GrossPriceProductTradePrice/ram:AppliedTradeAllowanceCharge/ram:ActualAmount))`

Charges on items seem to be explicitly allowed in A-3.2.1 and explicitly described in A-3.2.2 of EN16931-1: is there a particular reason why there seems to be a rule that rejects setting Indicator to  true?

**Comment by oriol** [comment]
BT-147 is the Item Price Discount, and it is bound to ram:GrossPriceProductTradePrice/ram:AppliedTradeAllowanceCharge/ram:ActualAmount when the ChargeIndicator is false(), indicating that this amount corresponds to an allowance and not to a charge. 

In the EN data model there is not an "Item Price Charge" and that's why this element is restricted out.
