### ISSUE TITLE
Update validation rules with latest codes

### ISSUE THREAD

**Issue by ConnectingEurope** [ConnectingEurope/eInvoicing-EN16931#271]
CEF has published a new version of the EAS code list as well as reviewed changes to all other code lists that are used in the EN and updated the listing of codes.

Please update the validation rules for the EN16931 in their next release so that all codes lists are supported as listed by CEF.

The attached Excel includes the full list of codes as they shall be supported in the EN. There are changes to 5 code lists. The table in the first sheet describes the changes in column F.

ISO 3166 -Added   extended country code XI
ICD code list - Added 0210,  0211, 0212, 0213
UNDID 7143 - Added TSU
EAS code list - Added 0210,   0211, 0212, 0213. Deprecated 9956
UOM rec20 and 21 - Updated to   Rec20r16+Rec21r11, adding 49 codes (see table)

In add addition to the excel files the listed codes are provided in a genericode format in the attached zip.

Attached files:
[EN16931 code lists values - used from 2021-05-17.xlsx](https://github.com/ConnectingEurope/eInvoicing-EN16931/files/6089893/EN16931.code.lists.values.-.used.from.2021-05-17.xlsx)
[EN16931 code lists values - genericodes -used from 2021-05-17.zip](https://github.com/ConnectingEurope/eInvoicing-EN16931/files/6089894/EN16931.code.lists.values.-.genericodes.-used.from.2021-05-17.zip)

**Comment by larsroelkerdenker** [comment]
please update UNTDID 1001 code values into the validation artefacts in the next version

- 875: Partial construction invoice
- 876: Partial final construction invoice
- 877: Final construction invoice

These entries are still missing in the validation artefacts. The values are essential for German construction invoicing

**Comment by svanteschubert** [comment]
Just a friendly reminder to the community:
1. The release of the CEN validation artefact, which includes the above EAS code list version 8, will be on Friday the 9th of April 2021.
2. The date when compliant implementations of EN 16931 - like any CIUSs as [Factur-X](http://fnfe-mpe.org/factur-x/) & [XRechnung](https://www.xoev.de/xrechnung-16828) - shall have the new code list version 8 in operation is at the end of Monday the 17th of May 2021.
3. There is a bi-annual schedule for the code lists and a [regular release schedule](https://ec.europa.eu/cefdigital/wiki/display/CEFDIGITAL/Registry+of+supporting+artefacts+to+implement+EN16931#RegistryofsupportingartefactstoimplementEN16931-Validationartefacts.2).

**Comment by svanteschubert** [comment]
> please update UNTDID 1001 code values into the validation artefacts in the next version
> ...

@larsroelkerdenker
The change requests for the EAS and/or VATEX code lists can be forwarded to the [CEF Service desk ](mailto:CEF-EINVOICING-SUPPORT@ec.europa.eu) at all times. This issue is likely only meant for the developers of the CEN validation artefacts.

**Comment by rkottmann** [comment]
>     please update UNTDID 1001 code values into the validation artefacts in the next version
>     ...
> 
> 
> @larsroelkerdenker
> The change requests for the EAS and/or VATEX code lists can be forwarded to the CEF Service desk at all times. This issue is likely only meant for the developers of the CEN validation artefacts.

As stated above, it is already since quiet some time in the UNTDID 1001, but for whatever reason does not seem to make it in the validationa artifacts. That's quiet a bumper.

**Comment by rkottmann** [comment]
> The date when compliant implementations of EN 16931 - like any CIUSs as Factur-X & XRechnung - shall have the new code list version 8 in operation is at the end of Monday the 17th of May 2021.

Who has a say on this? And is there somebody out there who can define "in operation"??

And if you use the term "SHALL" as in http://www.ietf.org/rfc/rfc2119.txt my simplpe answer: No way that XRechnung will meet this requirement.

And what about all the other CIUSes?

**Comment by svanteschubert** [comment]
> > ```
> > please update UNTDID 1001 code values into the validation artefacts in the next version
> > ...
> > ```
> > 
> > 
> > @larsroelkerdenker
> > The change requests for the EAS and/or VATEX code lists can be forwarded to the CEF Service desk at all times. This issue is likely only meant for the developers of the CEN validation artefacts.
> 
> As stated above, it is already since quiet some time in the UNTDID 1001, but for whatever reason does not seem to make it in the validationa artifacts. That's quiet a bumper.


@rkottmann **I do not find the above-mentioned codes within the CEF eInvoicing code lists managed by the Advisory Group.**

![2021-03-05_19-17-51](https://user-images.githubusercontent.com/825051/110156676-8f4c6d00-7de7-11eb-9d0c-74b894d542cf.png)

**Comment by rkottmann** [comment]
That's the issue. No one can find these codes in this however magically produced Excel. But they are in UNTDID1001 https://service.unece.org/trade/untdid/d20b/tred/tred1001.htm

since d19b and are very much required by the whole construction industry at least in whole Germany.

https://projekte.kosit.org/xrechnung/xrechnung/-/issues/44

**Comment by svanteschubert** [comment]
I do find it difficult to understand, too, why there is an Advisory Group being composed of two representatives from the following groups: 

* European Committee for Standardization Technical Committee 434 (CEN/TC434)
* Open Pan European Public Procurement On-Line Association (OpenPeppol)
* European E-Invoicing Service Providers Association (EESPA)
* Publications Office (OP)

Doing bi-annual releases of code lists instead of reusing the bi-annual releases of [code lists from UN/CEFACT](https://unece.org/trade/uncefact/cl-recommendations).

Obviously, not all codes from the code lists are being allowed to be used for EN16931 core-invoices.
But cherry-picking of semantics is already done by CEN TC 434: Picking the XML features of [UBL](http://docs.oasis-open.org/ubl/) & [UN/CEFACT CII](https://unece.org/trade/uncefact/xml-schemas) that deem appropriate for the European e-Invoice Core Semantic Model.

As I am an [editor](https://www.linkedin.com/in/svante-schubert-2913232/) of CEN TC 434 WG 1 (Semantics), I will find it out and report back.

PS: I believe it would be far better if we all would aim using a single semantic for the standard and therefore strive to align all three semantics of EN16931 in the future (both XML versions and EU (former [BII](https://en.wikipedia.org/wiki/Business_interoperability_interface)) semantic model).

**Comment by midran** [comment]
Hi,

The invoice type code list used in the EN is a subset of the 1001 and not the full set. When the code list is supported in full the EN states that it shall be the last version and then CEF monitors those and updates. But when there is a subset then it is the decision of TC434 exactly what the subset should be so CEF does not update those with any new codes unless instructed to do so by TC434. This request should therefore be directed towards TC434. Pls note that the deadline for change request to the codes was February 19th which has passed and also the spring release of the code list has now been published, consequently further changes would have to go to the Fall.

Regards
Georg

**Comment by MartinForsberg-Ecru** [comment]
A quick point on the use of code lists in CIUS in relation to what Svante wrote (on point 2)

A CIUS can very well use a subset of a code list and the authors/owners of the CIUS can decide on its own release and update schedule. 

/Martin


> 
>     2. The date when compliant implementations of EN 16931 - like any CIUSs as [Factur-X](http://fnfe-mpe.org/factur-x/) & [XRechnung](https://www.xoev.de/xrechnung-16828) - shall have the new code list version 8 in operation is at the end of Monday the 17th of May 2021.
>
