### ISSUE TITLE
BT-8 - Value added tax point date code- UNTDID 2005

### ISSUE THREAD

**Issue by sarafacchinetti** [ConnectingEurope/eInvoicing-EN16931#39]
In validation/ubl/schematron/codelist/EN16931-UBL-codes.sch:

<rule context="cac:InvoicePeriod/cbc:DescriptionCode" flag="fatal">
    <assert
      test="((not(contains(normalize-space(.), ' ')) and contains(' 5 29 72 ', concat(' ', normalize-space(.), ' '))))"
      flag="fatal">[BR-CL-06]-Value added tax point date code MUST be coded using a restriction of
      UNTDID 2475.</assert>
  </rule>

Why UNTDID 2475? The EN  16931-1:2017 for BT-8 refers to UNTDID 2005 (probably values could be Invoice document issue date –“3”, Delivery date, actual -“35”,  Paid to date – “432”)

**Comment by oriol** [comment]
The issue was that the CEFACT syntax had this data element bound to the code list 2475. When creating the validation artefacts it was agreed to use the same code lists for both syntaxes if possible. 

In this case, the semantic data elements (semantics is what the EN is all about) are in both code lists, therefore, it was agreed to switch from 2005 to 2475 because the semantics on the data elements is preserved.

**Comment by sarafacchinetti** [comment]
In the published EN 16931-1:2017 norm there is this indication for BT-8:
"The code shall distinguish between the following entries of UNTDID 2005:
- Invoice document issue date
- Delivery date, actual
- Paid to date 
The Value added tax point date code is used if the Value added tax point date is not known when the invoice is issued. The use of BT-8 and BT-7 is mutually exclusive."

If you plan to use UNTDID 2475 perhaps you'd probably need to propose a corrigendum to the norm.

**Comment by oriol** [comment]
UBL validation artefacts are now again using the UNTDID 2005 codes to validate BT-8

**Comment by phax** [comment]
But CII still uses UNTDID 2475 and this an issue
