### ISSUE TITLE
BT 120 and BT 121 fire warnings

### ISSUE THREAD

**Issue by midran** [ConnectingEurope/eInvoicing-EN16931#88]
When business terms BT 120 and 121 are included they fire warnings.

**Comment by phax** [comment]
Can you please elaborate a bit? Thanks
Ideally, do you have an example?

**Comment by midran** [comment]
[UBL full invoice - Copy.txt](https://github.com/CenPC434/validation/files/2686695/UBL.full.invoice.-.Copy.txt)

The existance of either bt 120 or bt 121 is required if vat category code is E. However if they exist it fires warnings that they should not exist. Maybe only one should exist but then that is unclear from the warning.

**Comment by oriol** [comment]
BT-120 and BT-121 refer to the TaxExemptionReasonCode and TaxExemptionReason at TaxSubTotal level. You can define these exemption reasons when you define the Tax at cac:TaxTotal/cac:TaxSubtotal level, but it is not allowed to define them when you are defining the taxes at Allowance Charge level. That's why there are warnings firing with the example.
